# Generated by Django 4.2.22 on 2025-06-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customimage',
            name='processed_image',
        ),
    ]
