# Generated by Django 4.2.22 on 2025-06-04 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customimage_resized_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('og_image_width', models.IntegerField()),
                ('og_image_height', models.IntegerField()),
                ('resized_image_width', models.IntegerField(blank=True, null=True)),
                ('resized_image_height', models.IntegerField(blank=True, null=True)),
                ('upload_time', models.DateTimeField()),
                ('MIME_type', models.CharField(max_length=31)),
                ('og_file_name', models.CharField(max_length=255)),
                ('resized_file_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customimage',
            name='meta_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.imagemetadata'),
        ),
    ]
